//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_RESTfulApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string BuyPrice { get; set; }
        public string SalePrice { get; set; }
        public string Stock { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string Brand { get; set; }
        public string Approved { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
