//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_RESTfulApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePart
    {
        public int PartID { get; set; }
        public string CarMfgID { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string Fitment { get; set; }
        public string Vehicle { get; set; }
        public string CostPrice { get; set; }
        public string SalePrice { get; set; }
        public string Qty { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> VModelId { get; set; }
    }
}
