//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_RESTfulApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public int Id { get; set; }
        public string Yearr { get; set; }
        public string Model { get; set; }
        public int MakerId { get; set; }
    }
}
